const quizData = [
  {
    question: 'How old is Intissar?',
    a: '10',
    b: '17',
    c: '21',
    d: '110',
    correct: 'c',
  },
  {
    question: 'What is the most programming language in 2019?',
    a: 'Java',
    b: 'C',
    c: 'Python',
    d: 'Javascript',
    correct: 'd',
  },
  {
    question: 'Who is the President of US?',
    a: 'Intissar jo',
    b: 'Donald Trump',
    c: 'Ivan Saldano',
    d: 'Mihai Andrei',
    correct: 'b',
  },
  {
    question: 'What does HTML stand for?',
    a: 'Hypertext Markup Language',
    b: 'Cascading Style Sheet',
    c: 'Jason Object Notation',
    d: 'Helicopters Terminals Motorboats Lamborginis',
    correct: 'a',
  },
  {
    question: 'What year was Javascript Launched?',
    a: '1996',
    b: '1995',
    c: '1994',
    d: 'none of the obove',
    correct: 'd',
  },
];
